.TH ROTATE-LINUX-PASSWORD 1 "06 Mar 2023" "rotate-linux-password" "General Command Manual"
.SH NAME
rotate-linux-password.sh - script to rotate the password of a Linux user account
.SH SYNOPSIS
.B rotate-linux-password.sh
\fB<username>\fR
.SH DESCRIPTION
The \fBrotate-linux-password.sh\fR script is used to rotate the password of a Linux user account. This script takes one option which is used to specify the username whose password should be rotated. If the username option is not provided, the script will exit with an error message.
.SH OPTIONS
.TP
\fB<username>\fR
Specify the username whose password should be rotated.
.SH USAGE
To use this script, execute the following command:
.B
rotate-linux-password.sh <username>
.SH EXAMPLES
To rotate the password for user "jdoe", use the following command:
.B
rotate-linux-password.sh jdoe
.SH AUTHOR
Salman Butt <cn137@protonmail.com>
.SH "REPORTING BUGS"
Report bugs to https://github.com/cn137/painless-password-rotation/issues.
.SH COPYRIGHT
Copyright (c) 2023 Salman Butt.
.br

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
